# Sigpatches for 1106, plus load osBbHackFlags from osTvType field in ticket

before_hash = "0059DEB22F85BC1C7BFCDB16FEBA6DD057548053"

# Checking hashes is optional
#after_hash = "052646B6469ABC4DB2923419B54CC007BEFED57A"

[sk]
patches = [
    { offset = 0x0C10, from = 0x14620054, to = 0x14630054 },
    { offset = 0x0FEC, from = 0x2645FFDC, to = 0x27A50010 },
    { offset = 0x161C, from = 0x02002821, to = 0x00042821 },
    { offset = 0x33E4, from = 0x24A50004, to = 0x24850000 },
]

[sa2]
patches = [
    # This ↓↓↓↓ is the patch that makes the redirection persistent
    { offset = 0x0010A4, from = 0xAC20038C, to = 0x00000000 },
    # This ↓↓↓↓ is the patch that loads osBbHackFlags from the ticket
    { offset = 0x0241E8, from = 0xAC220300, to = 0xAC22038C },

    # (This one's for the sigpatches)
    { offset = 0x01C248, from = 0x27A50304, to = 0x27A50100 },
]
